In [17]:
import numpy as np
import pandas as pd
import pyarrow
import random

pd.set_option('display.max_columns', 300)
pd.set_option('display.max_rows',50)

bookings_file='./Datasets/Bookings.csv'

In [18]:
###Dataset Bookings
bookings = pd.read_csv(bookings_file,low_memory=False, encoding='utf-8')
bookings.shape

(67682, 36)

In [19]:
bookings.describe(include='all')

,Operaciones,Estado,Id,Proveedor,ID Res Proveedor,ID Res Civitatis,Res Relacionada,Nombre,Apellidos Cliente,Teléfono,Email Cliente,fecha traslado,Hora Traslado,Núm. Pasajeros,Tipo vehículo,Tipo desplazamiento,Ruta,Importe Total,Anticipo,Comisión Llevame,Pago en vehículo,Prepago,Comentarios,Ciudad Origen,Dirección,Hotel,Núm Vuelo,editar,Link confimación,Link reserva,Creado,Cambiado,Fecha reserva,Megarow links,Email Cliente.1,Recordatorio Cliente
count,0.0,17851,67682.000000,62351,61528,67675,44862,67682,67682,67666,67281,67682,67682,67678.000000,67682,67673,67682,66987.000000,11363.000000,55393.000000,67632.000000,67682.000000,12564,40694,67423,28418,67077,67682,1706,1707,67682,67682,67682,67682,67281,67682.000000
unique,NaN,2,NaN,16,60173,67662,44818,7251,31506,38795,36144,47180,320,NaN,14,5,45,NaN,NaN,NaN,NaN,NaN,10112,3331,23364,9528,26795,1,1,1,26949,18669,38204,1,36144,NaN
top,NaN,modificado,NaN,MarcoBPS,Hecho,T298144,T298170,Javier,Gonzalez,(+34) 699904133,inpetransfer@gmail.com,2023/12/23 17:50:00,15:00,NaN,SUV6,Aeropuerto - Ciudad,Aeropuerto JFK - Manhattan,NaN,NaN,NaN,NaN,NaN,Conductor que hable español,Madrid,"Hotel Riu Plaza New York Times Square, West 46...",Hotel Pennsylvania,IB6251,Editar,confirmación,reserva,2017/03/29 - 15:07,2023/11/01 - 11:03,2014/04/01 - 15:07,abiertatexto E-mail\nver confirmación\n,inpetransfer@gmail.com,NaN
freq,NaN,12880,NaN,13578,1136,2,3,875,195,29,306,16,2732,NaN,29056,36972,29383,NaN,NaN,NaN,NaN,NaN,23,6788,2395,435,1192,67682,1706,1707,394,856,132,67682,306,NaN
mean,NaN,NaN,45350.957064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.873519,NaN,NaN,NaN,134.245983,34.119379,11.726716,94.661803,0.819066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.788393
std,NaN,NaN,19560.189040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.165635,NaN,NaN,NaN,44.898539,12.976959,3.735653,33.310769,0.384967,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.408451
min,NaN,NaN,11479.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,-84.500000,0.000000,-10.000000,-405.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
25%,NaN,NaN,28411.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,106.500000,25.000000,10.000000,75.250000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
50%,NaN,NaN,45353.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,125.000000,35.000000,10.000000,90.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
75%,NaN,NaN,62295.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,142.500000,35.000000,12.500000,102.750000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
max,NaN,NaN,79224.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.000000,NaN,NaN,NaN,625.000000,245.000000,45.000000,527.750000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000

In [20]:
#bookings.head()
bookings.loc[random.sample(range(0, bookings.shape[0]), 5)]

,Operaciones,Estado,Id,Proveedor,ID Res Proveedor,ID Res Civitatis,Res Relacionada,Nombre,Apellidos Cliente,Teléfono,Email Cliente,fecha traslado,Hora Traslado,Núm. Pasajeros,Tipo vehículo,Tipo desplazamiento,Ruta,Importe Total,Anticipo,Comisión Llevame,Pago en vehículo,Prepago,Comentarios,Ciudad Origen,Dirección,Hotel,Núm Vuelo,editar,Link confimación,Link reserva,Creado,Cambiado,Fecha reserva,Megarow links,Email Cliente.1,Recordatorio Cliente
30270,NaN,cancelado,41783,NaN,NaN,T1196937,T1196938,Sebastian,Leon Plasencia,(+34) 638059000,sebastianleon@jardin-tropical.com,2021/12/18 19:30:00,19:30,7.0,Limo 8,Aeropuerto - Ciudad,Aeropuerto JFK - Manhattan,235.0,NaN,20.0,162.75,1,NaN,Madrid,"Cambria Hotel Rooftop, 123 28th St, Nueva York...",NaN,Iberia 6253,Editar,NaN,NaN,2021/10/03 - 07:33,2021/12/14 - 17:30,2021/10/02 - 13:35,abiertatexto E-mail\nver confirmación\n,sebastianleon@jardin-tropical.com,0
33356,NaN,modificado,44869,800S,T1262903,T1262903,T1262902,Cécile,Flaire,(+33) 677774352,cecilearyo@gmail.com,2022/04/20 16:15:00,16:15,7.0,Furgoneta de 10 plazas,Ciudad - Aeropuerto,Manhattan - Aeropuerto JFK,213.0,NaN,20.0,147.75,1,NaN,NaN,New York Hotel Hilton,NaN,Air France AF11,Editar,NaN,NaN,2022/03/19 - 15:00,2022/04/19 - 16:00,2022/03/19 - 14:34,abiertatexto E-mail\nver confirmación\n,cecilearyo@gmail.com,1
31667,NaN,NaN,43180,MarcoBPS,T1229877,T1229877,T1229876,Irene,Roselló Muñoz,(+34) +34664468691,irenerosellomunoz@gmail.com,2022/01/07 16:00:00,16:00,6.0,SUV6,Ciudad - Aeropuerto,Manhattan - Aeropuerto Newark,160.0,NaN,12.0,112.75,1,NaN,NaN,"223 West 18th Street, Nueva York, Nueva York 1...",NaN,United Airlines UA120,Editar,NaN,NaN,2021/12/25 - 18:00,2023/11/01 - 11:21,2021/12/23 - 13:30,abiertatexto E-mail\nver confirmación\n,irenerosellomunoz@gmail.com,1
44018,NaN,NaN,55534,Patricio,T1455890,T1455890,NaN,Pablo,Perez Barreto,(+34) 699882612,perezbarretopablo@gmail.com,2022/11/15 15:05:00,15:05,2.0,Sedan,Aeropuerto - Ciudad,Aeropuerto JFK - Manhattan,106.5,NaN,7.5,77.75,1,Somos una pareja que volamos desde Madrid. Pab...,New York,TownePlace Suites by Marriott New York Manhatt...,NaN,IBERIA IB6251,Editar,NaN,NaN,2022/11/14 - 15:30,2022/11/14 - 16:15,2022/11/14 - 16:03,abiertatexto E-mail\nver confirmación\n,perezbarretopablo@gmail.com,1
61741,NaN,NaN,73279,MarcoBPS,T1766550,T1766550,T1766551,Paula,Rava,(+34) 657681881,paularava07@gmail.com,2023/11/20 15:05:00,15:05,2.0,Sedan,Aeropuerto - Ciudad,Aeropuerto JFK - Manhattan,112.0,NaN,10.0,77.75,1,NaN,MADRID,"Hotel Edison, West 47th Street, Nueva York, EE...",NaN,IBERIA IB6251,Editar,NaN,NaN,2023/10/28 - 04:30,2023/11/19 - 15:15,2023/10/28 - 05:05,abiertatexto E-mail\nver confirmación\n,paularava07@gmail.com,1

In [21]:
print(bookings.dtypes)

Operaciones             float64
Estado                   object
Id                        int64
Proveedor                object
ID Res Proveedor         object
ID Res Civitatis         object
Res Relacionada          object
Nombre                   object
Apellidos Cliente        object
Teléfono                 object
Email Cliente            object
fecha traslado           object
Hora Traslado            object
Núm. Pasajeros          float64
Tipo vehículo            object
Tipo desplazamiento      object
Ruta                     object
Importe Total           float64
Anticipo                float64
Comisión Llevame        float64
Pago en vehículo        float64
Prepago                   int64
Comentarios              object
Ciudad Origen            object
Dirección                object
Hotel                    object
Núm Vuelo                object
editar                   object
Link confimación         object
Link reserva             object
Creado                   object
Cambiado                 object
Fecha reserva            object
Megarow links            object
Email Cliente.1          object
Recordatorio Cliente      int64
dtype: object

In [22]:
#Decide which columns are being kept
print(bookings.columns)
all=['Operaciones', 'Estado', 'Id', 'Proveedor', 'ID Res Proveedor',
       'ID Res Civitatis', 'Res Relacionada', 'Nombre', 'Apellidos Cliente',
       'Teléfono', 'Email Cliente', 'fecha traslado', 'Hora Traslado',
       'Núm. Pasajeros', 'Tipo vehículo', 'Tipo desplazamiento', 'Ruta',
       'Importe Total', 'Anticipo', 'Comisión Llevame', 'Pago en vehículo',
       'Prepago', 'Comentarios', 'Ciudad Origen', 'Dirección', 'Hotel',
       'Núm Vuelo', 'editar', 'Link confimación', 'Link reserva', 'Creado',
       'Cambiado', 'Fecha reserva', 'Megarow links', 'Email Cliente.1',
       'Recordatorio Cliente']
keeping=['Estado', 'Proveedor', 'ID Res Civitatis', 'Res Relacionada', 'Nombre',
         'fecha traslado', 'Hora Traslado', 'Núm. Pasajeros', 'Tipo vehículo', 
         'Tipo desplazamiento', 'Ruta', 'Importe Total', 'Comisión Llevame', 
         'Pago en vehículo', 'Comentarios', 'Ciudad Origen', 'Dirección', 
         'Hotel', 'Núm Vuelo', 'Cambiado', 'Fecha reserva']
bookings=bookings[keeping]

Index(['Operaciones', 'Estado', 'Id', 'Proveedor', 'ID Res Proveedor',
       'ID Res Civitatis', 'Res Relacionada', 'Nombre', 'Apellidos Cliente',
       'Teléfono', 'Email Cliente', 'fecha traslado', 'Hora Traslado',
       'Núm. Pasajeros', 'Tipo vehículo', 'Tipo desplazamiento', 'Ruta',
       'Importe Total', 'Anticipo', 'Comisión Llevame', 'Pago en vehículo',
       'Prepago', 'Comentarios', 'Ciudad Origen', 'Dirección', 'Hotel',
       'Núm Vuelo', 'editar', 'Link confimación', 'Link reserva', 'Creado',
       'Cambiado', 'Fecha reserva', 'Megarow links', 'Email Cliente.1',
       'Recordatorio Cliente'],
      dtype='object')

In [23]:
bookings.columns

Index(['Estado', 'Proveedor', 'ID Res Civitatis', 'Res Relacionada', 'Nombre',
       'fecha traslado', 'Hora Traslado', 'Núm. Pasajeros', 'Tipo vehículo',
       'Tipo desplazamiento', 'Ruta', 'Importe Total', 'Comisión Llevame',
       'Pago en vehículo', 'Comentarios', 'Ciudad Origen', 'Dirección',
       'Hotel', 'Núm Vuelo', 'Cambiado', 'Fecha reserva'],
      dtype='object')

In [24]:
#Translate Column Names
new_names = bookings.columns
new_names=[str.lower(x) for x in new_names]
new_names=['status', 'supplier', 'booking_id', 'roundtrip_id', 'name', 'pickup_date', 
           'pickup_time', 'number_of_passenger', 'vehicle_type', 'route_type', 'route', 
           'total_price', 'total_comission', 'total_driver', 'special_notes', 'city_of_departure', 
           'address', 'hotel', 'flight_number', 'last_update_date', 'booking_date']
bookings.columns=new_names

In [25]:
#Convert to Datetimes
#Example of what the source has: 2016/09/01 19:00:00
bookings['pickup_date'] = pd.to_datetime(bookings['pickup_date'])
bookings['last_update_date'] = pd.to_datetime(bookings['last_update_date'])
bookings['booking_date'] = pd.to_datetime(bookings['booking_date'])

In [26]:
#Remove some personal bookings that will have strange unconventional IDs.
#bookings.sort_values(len(str(bookings['booking_id'])), ascending=False)
#pd.set_option('display.max_rows', 1000)
filter=bookings['booking_id'].astype(str).map(len)>13
sum(filter) #total 18
bookings=bookings[~filter]
bookings.shape

(67664, 21)

In [27]:
#Remove some cancelled bookings that don't have ID
filter=bookings['booking_id'].isna()
print(sum(filter))
bookings=bookings[~filter]

7

In [28]:
#Convert Number of Passengers to Integer
bookings['number_of_passenger']=bookings['number_of_passenger'].fillna(0)
bookings['number_of_passenger']=bookings['number_of_passenger'].astype(int)

In [29]:
# No String conversion for now.

#Convert to Strings (from object type)
#bookings['status']=bookings['status'].astype(str) 
#=str(bookings['booking_id']).encode('utf8')
#bookings['roundtrip_id']=
#print(bookings['roundtrip_id'].astype('|S')) # which will by default set the length to the max len it encounters
#bookings['name']=
#print(bookings['name'].astype(str))
#.astype('|S')
'''
bookings['vehicle_type']=bookings['vehicle_type'].astype('|S')
bookings['route_type']=bookings['route_type'].astype('|S')
bookings['route']=bookings['route'].astype('|S')
bookings['special_notes']=bookings['special_notes'].astype('|S')
bookings['city_of_departure']=bookings['city_of_departure'].astype('|S')
bookings['address']=bookings['address'].astype('|S')
bookings['hotel']=bookings['hotel'].astype('|S')
bookings['flight_number']=bookings['flight_number'].astype('|S')'''

"\nbookings['vehicle_type']=bookings['vehicle_type'].astype('|S')\nbookings['route_type']=bookings['route_type'].astype('|S')\nbookings['route']=bookings['route'].astype('|S')\nbookings['special_notes']=bookings['special_notes'].astype('|S')\nbookings['city_of_departure']=bookings['city_of_departure'].astype('|S')\nbookings['address']=bookings['address'].astype('|S')\nbookings['hotel']=bookings['hotel'].astype('|S')\nbookings['flight_number']=bookings['flight_number'].astype('|S')"

In [30]:
#Truncate: Email,'Driver_price', 'commission', 'sale_price'.


#Need to change data types
unique_values_set = set(bookings['supplier'])
#print(unique_values_set)
bookings.supplier.nunique()
bookings['supplier'].unique()

array(['FCLimo', 'NewDay', 'Golden Class Limo', 'PeterLimo', 'DH2L',
       'Efrain', nan, 'Nestor', 'Camila', 'FRANKLYN', 'LXNY', 'HUGO',
       'Best Limo', '800S', 'MarcoBPS', 'Patricio', 'Johnny Limo'],
      dtype=object)

In [31]:
#Take a look at some expected fixed values

#Need to change data types
unique_values_set = set(bookings['status'])
unique_values_set

{'cancelado', 'modificado', nan}

In [32]:
#After all the changes, we proceed to save the changes in a file.
import os
outname = 'all_bookings2.0.csv'
outdir = './Datasets'
if not os.path.exists(outdir):
    os.mkdir(outdir)
fullname = os.path.join(outdir, outname)    

bookings.to_csv(fullname, header=True, index=False)
print("Saved!")

Saved!