In [1]:
import numpy as np
import pandas as pd
import pyarrow
import random

pd.set_option('display.max_columns', 300)
pd.set_option('display.max_rows',50)

bookings_file='./Datasets/Bookings.csv'

In [2]:
###Dataset Bookings
bookings = pd.read_csv(bookings_file,low_memory=False, encoding='utf-8')
bookings.shape

(67682, 36)

In [3]:
bookings.describe(include='all')

,Operaciones,Estado,Id,Proveedor,ID Res Proveedor,ID Res Civitatis,Res Relacionada,Nombre,Apellidos Cliente,Teléfono,Email Cliente,fecha traslado,Hora Traslado,Núm. Pasajeros,Tipo vehículo,Tipo desplazamiento,Ruta,Importe Total,Anticipo,Comisión Llevame,Pago en vehículo,Prepago,Comentarios,Ciudad Origen,Dirección,Hotel,Núm Vuelo,editar,Link confimación,Link reserva,Creado,Cambiado,Fecha reserva,Megarow links,Email Cliente.1,Recordatorio Cliente
count,0.0,17851,67682.000000,62351,61528,67675,44862,67682,67682,67666,67281,67682,67682,67678.000000,67682,67673,67682,66987.000000,11363.000000,55393.000000,67632.000000,67682.000000,12564,40694,67423,28418,67077,67682,1706,1707,67682,67682,67682,67682,67281,67682.000000
unique,NaN,2,NaN,16,60173,67662,44818,7251,31506,38795,36144,47180,320,NaN,14,5,45,NaN,NaN,NaN,NaN,NaN,10112,3331,23364,9528,26795,1,1,1,26949,18669,38204,1,36144,NaN
top,NaN,modificado,NaN,MarcoBPS,Hecho,T298144,T298170,Javier,Gonzalez,(+34) 699904133,inpetransfer@gmail.com,2023/12/23 17:50:00,15:00,NaN,SUV6,Aeropuerto - Ciudad,Aeropuerto JFK - Manhattan,NaN,NaN,NaN,NaN,NaN,Conductor que hable español,Madrid,"Hotel Riu Plaza New York Times Square, West 46...",Hotel Pennsylvania,IB6251,Editar,confirmación,reserva,2017/03/29 - 15:07,2023/11/01 - 11:03,2014/04/01 - 15:07,abiertatexto E-mail\nver confirmación\n,inpetransfer@gmail.com,NaN
freq,NaN,12880,NaN,13578,1136,2,3,875,195,29,306,16,2732,NaN,29056,36972,29383,NaN,NaN,NaN,NaN,NaN,23,6788,2395,435,1192,67682,1706,1707,394,856,132,67682,306,NaN
mean,NaN,NaN,45350.957064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.873519,NaN,NaN,NaN,134.245983,34.119379,11.726716,94.661803,0.819066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.788393
std,NaN,NaN,19560.189040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.165635,NaN,NaN,NaN,44.898539,12.976959,3.735653,33.310769,0.384967,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.408451
min,NaN,NaN,11479.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,-84.500000,0.000000,-10.000000,-405.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
25%,NaN,NaN,28411.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,106.500000,25.000000,10.000000,75.250000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
50%,NaN,NaN,45353.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,125.000000,35.000000,10.000000,90.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
75%,NaN,NaN,62295.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,142.500000,35.000000,12.500000,102.750000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
max,NaN,NaN,79224.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.000000,NaN,NaN,NaN,625.000000,245.000000,45.000000,527.750000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000

In [4]:
#bookings.head()
bookings.loc[random.sample(range(0, bookings.shape[0]), 5)]

,Operaciones,Estado,Id,Proveedor,ID Res Proveedor,ID Res Civitatis,Res Relacionada,Nombre,Apellidos Cliente,Teléfono,Email Cliente,fecha traslado,Hora Traslado,Núm. Pasajeros,Tipo vehículo,Tipo desplazamiento,Ruta,Importe Total,Anticipo,Comisión Llevame,Pago en vehículo,Prepago,Comentarios,Ciudad Origen,Dirección,Hotel,Núm Vuelo,editar,Link confimación,Link reserva,Creado,Cambiado,Fecha reserva,Megarow links,Email Cliente.1,Recordatorio Cliente
3090,NaN,NaN,14569,DH2L,Hecho,T120945,NaN,Ernestina,Fernandez Garcia,+34 617431638,ernestinafg@yahoo.es,2015/08/17 15:50:00,15:50,4.0,SUV6,Aeropuerto - Ciudad,Aeropuerto Newark - Brooklyn,160.00,35.0,NaN,125.00,0,NaN,Porto,181 3rd Avenue Brooklyn New York 11217,Fairfield Inn & Suites by Marriott,TAP Portugal,Editar,NaN,NaN,2017/03/29 - 15:15,2023/11/01 - 10:49,2015/08/15 - 15:15,abiertatexto E-mail\nver confirmación\n,ernestinafg@yahoo.es,0
33432,NaN,modificado,44945,MarcoBPS,T1264144,T1264144,NaN,Sahra,Bouzerda,(+33) 0659087800,sbouzerda12@gmail.com,2022/03/22 18:00:00,18:00,2.0,Sedan,Aeropuerto - Ciudad,Aeropuerto JFK - Manhattan,106.50,NaN,7.5,77.75,1,NaN,Toulouse,"Westgate New York Grand Central, East 42nd Str...",NaN,AF006,Editar,NaN,NaN,2022/03/22 - 03:00,2022/03/22 - 08:39,2022/03/22 - 02:30,abiertatexto E-mail\nver confirmación\n,sbouzerda12@gmail.com,1
11887,NaN,NaN,23367,LXNY,T298109,T298109,NaN,Eliseo,Mansilla,+56 974307474,CZUNIGA.OSORIO@GMAIL.COM,2018/01/03 04:00:00,04:00,2.0,Sedan,Ciudad - Aeropuerto,Manhattan - Aeropuerto LaGuardia,NaN,NaN,NaN,50.00,0,NaN,NaN,302 west 47 th street,Econo lodge time square,American airlines 2266,Editar,NaN,NaN,2017/12/28 - 09:34,2018/05/28 - 14:41,2017/12/27 - 18:38,abiertatexto E-mail\nver confirmación\n,CZUNIGA.OSORIO@GMAIL.COM,1
28019,NaN,NaN,39532,Best Limo,T1057648,T1057648,T1057651,Luis Maria,Ysa Valle,(+34) 670974931,lmysavalle@hotmail.com,2019/12/29 21:30:00,21:30,2.0,Sedan,Aeropuerto - Ciudad,Aeropuerto JFK - Queens,105.00,NaN,10.0,72.75,1,NaN,Madrid,"3Avenue, long island city 11101/2123197000",Z nyc,norwegian air shuttle. DY 7703,Editar,NaN,NaN,2019/12/25 - 13:00,2019/12/29 - 23:25,2019/12/25 - 13:33,abiertatexto E-mail\nver confirmación\n,lmysavalle@hotmail.com,1
61521,NaN,cancelado,73059,NaN,NaN,T1762836,T1762841,Andres Francisco,Feijo Alvarez,(+34) 639635391,aredondh@gmail.com,2023/12/23 18:55:00,18:55,5.0,SUV6,Aeropuerto - Ciudad,Aeropuerto JFK - Manhattan,146.25,NaN,12.5,102.75,1,NaN,MADRID,"Hotel Riu Plaza Manhattan Times Square, West 4...",NaN,AY5655,Editar,NaN,NaN,2023/10/24 - 12:30,2023/11/01 - 12:26,2023/10/24 - 13:14,abiertatexto E-mail\nver confirmación\n,aredondh@gmail.com,0

In [5]:
print(bookings.dtypes)

Operaciones             float64
Estado                   object
Id                        int64
Proveedor                object
ID Res Proveedor         object
ID Res Civitatis         object
Res Relacionada          object
Nombre                   object
Apellidos Cliente        object
Teléfono                 object
Email Cliente            object
fecha traslado           object
Hora Traslado            object
Núm. Pasajeros          float64
Tipo vehículo            object
Tipo desplazamiento      object
Ruta                     object
Importe Total           float64
Anticipo                float64
Comisión Llevame        float64
Pago en vehículo        float64
Prepago                   int64
Comentarios              object
Ciudad Origen            object
Dirección                object
Hotel                    object
Núm Vuelo                object
editar                   object
Link confimación         object
Link reserva             object
Creado                   object
Cambiado                 object
Fecha reserva            object
Megarow links            object
Email Cliente.1          object
Recordatorio Cliente      int64
dtype: object

In [6]:
#Decide which columns are being kept
print(bookings.columns)
all=['Operaciones', 'Estado', 'Id', 'Proveedor', 'ID Res Proveedor',
       'ID Res Civitatis', 'Res Relacionada', 'Nombre', 'Apellidos Cliente',
       'Teléfono', 'Email Cliente', 'fecha traslado', 'Hora Traslado',
       'Núm. Pasajeros', 'Tipo vehículo', 'Tipo desplazamiento', 'Ruta',
       'Importe Total', 'Anticipo', 'Comisión Llevame', 'Pago en vehículo',
       'Prepago', 'Comentarios', 'Ciudad Origen', 'Dirección', 'Hotel',
       'Núm Vuelo', 'editar', 'Link confimación', 'Link reserva', 'Creado',
       'Cambiado', 'Fecha reserva', 'Megarow links', 'Email Cliente.1',
       'Recordatorio Cliente']
keeping=['Estado', 'Proveedor', 'ID Res Civitatis', 'Res Relacionada', 'Nombre',
         'fecha traslado', 'Hora Traslado', 'Núm. Pasajeros', 'Tipo vehículo', 
         'Tipo desplazamiento', 'Ruta', 'Importe Total', 'Comisión Llevame', 
         'Pago en vehículo', 'Comentarios', 'Ciudad Origen', 'Dirección', 
         'Hotel', 'Núm Vuelo', 'Cambiado', 'Fecha reserva']
bookings=bookings[keeping]

Index(['Operaciones', 'Estado', 'Id', 'Proveedor', 'ID Res Proveedor',
       'ID Res Civitatis', 'Res Relacionada', 'Nombre', 'Apellidos Cliente',
       'Teléfono', 'Email Cliente', 'fecha traslado', 'Hora Traslado',
       'Núm. Pasajeros', 'Tipo vehículo', 'Tipo desplazamiento', 'Ruta',
       'Importe Total', 'Anticipo', 'Comisión Llevame', 'Pago en vehículo',
       'Prepago', 'Comentarios', 'Ciudad Origen', 'Dirección', 'Hotel',
       'Núm Vuelo', 'editar', 'Link confimación', 'Link reserva', 'Creado',
       'Cambiado', 'Fecha reserva', 'Megarow links', 'Email Cliente.1',
       'Recordatorio Cliente'],
      dtype='object')

In [7]:
bookings.columns

Index(['Estado', 'Proveedor', 'ID Res Civitatis', 'Res Relacionada', 'Nombre',
       'fecha traslado', 'Hora Traslado', 'Núm. Pasajeros', 'Tipo vehículo',
       'Tipo desplazamiento', 'Ruta', 'Importe Total', 'Comisión Llevame',
       'Pago en vehículo', 'Comentarios', 'Ciudad Origen', 'Dirección',
       'Hotel', 'Núm Vuelo', 'Cambiado', 'Fecha reserva'],
      dtype='object')

In [8]:
#Translate Column Names
new_names = bookings.columns
new_names=[str.lower(x) for x in new_names]
new_names=['status', 'supplier', 'booking_id', 'roundtrip_id', 'name', 'pickup_date', 
           'pickup_time', 'number_of_passenger', 'vehicle_type', 'route_type', 'route', 
           'total_price', 'total_comission', 'total_driver', 'special_notes', 'city_of_departure', 
           'address', 'hotel', 'flight_number', 'last_update_date', 'booking_date']
bookings.columns=new_names

In [9]:
#Convert to Datetimes
#Example of what the source has: 2016/09/01 19:00:00
bookings['pickup_date'] = pd.to_datetime(bookings['pickup_date'])
bookings['last_update_date'] = pd.to_datetime(bookings['last_update_date'])
bookings['booking_date'] = pd.to_datetime(bookings['booking_date'])

In [10]:
#Remove some personal bookings that will have strange unconventional IDs.
#bookings.sort_values(len(str(bookings['booking_id'])), ascending=False)
#pd.set_option('display.max_rows', 1000)
filter=bookings['booking_id'].astype(str).map(len)>13
sum(filter) #total 18
bookings=bookings[~filter]
bookings.shape

(67664, 21)

In [11]:
#Remove some cancelled bookings that don't have ID
filter=bookings['booking_id'].isna()
print(sum(filter))
bookings=bookings[~filter]

7

In [12]:
#Convert Number of Passengers to Integer
bookings['number_of_passenger']=bookings['number_of_passenger'].fillna(0)
bookings['number_of_passenger']=bookings['number_of_passenger'].astype(int)

In [13]:
# No String conversion for now.

#Convert to Strings (from object type)
#bookings['status']=bookings['status'].astype(str) 
#=str(bookings['booking_id']).encode('utf8')
#bookings['roundtrip_id']=
#print(bookings['roundtrip_id'].astype('|S')) # which will by default set the length to the max len it encounters
#bookings['name']=
#print(bookings['name'].astype(str))
#.astype('|S')
'''
bookings['vehicle_type']=bookings['vehicle_type'].astype('|S')
bookings['route_type']=bookings['route_type'].astype('|S')
bookings['route']=bookings['route'].astype('|S')
bookings['special_notes']=bookings['special_notes'].astype('|S')
bookings['city_of_departure']=bookings['city_of_departure'].astype('|S')
bookings['address']=bookings['address'].astype('|S')
bookings['hotel']=bookings['hotel'].astype('|S')
bookings['flight_number']=bookings['flight_number'].astype('|S')'''

"\nbookings['vehicle_type']=bookings['vehicle_type'].astype('|S')\nbookings['route_type']=bookings['route_type'].astype('|S')\nbookings['route']=bookings['route'].astype('|S')\nbookings['special_notes']=bookings['special_notes'].astype('|S')\nbookings['city_of_departure']=bookings['city_of_departure'].astype('|S')\nbookings['address']=bookings['address'].astype('|S')\nbookings['hotel']=bookings['hotel'].astype('|S')\nbookings['flight_number']=bookings['flight_number'].astype('|S')"

In [14]:
#Truncate: Email,'Driver_price', 'commission', 'sale_price'.


#Need to change data types
unique_values_set = set(bookings['supplier'])
#print(unique_values_set)
bookings.supplier.nunique()
bookings['supplier'].unique()

array(['FCLimo', 'NewDay', 'Golden Class Limo', 'PeterLimo', 'DH2L',
       'Efrain', nan, 'Nestor', 'Camila', 'FRANKLYN', 'LXNY', 'HUGO',
       'Best Limo', '800S', 'MarcoBPS', 'Patricio', 'Johnny Limo'],
      dtype=object)

In [15]:
#Take a look at some expected fixed values

#Need to change data types
unique_values_set = set(bookings['status'])
unique_values_set

{'cancelado', 'modificado', nan}

In [17]:
#Find and remove duplicates. Perfect only 13.
test=bookings.groupby(['booking_id']).size().reset_index(name='count')
L=test[test['count'].astype(int)>=2]['booking_id'].tolist()
print(L)
print(len(L))#13
print(bookings.shape)#(67657, 21)
bookings=bookings.drop_duplicates(subset='booking_id', keep="last", inplace=False)
print(bookings.shape)#(67644, 21)

['T298117', 'T298129', 'T298133', 'T298134', 'T298139', 'T298144', 'T298146', 'T298147', 'T298170', 'T298194', 'T298210', 'T298211', 'T298838']
13
(67657, 21)
(67644, 21)

In [18]:
#After all the changes, we proceed to save the changes in a file.
import os
outname = 'all_bookings2.0.csv'
outdir = './Datasets'
if not os.path.exists(outdir):
    os.mkdir(outdir)
fullname = os.path.join(outdir, outname)    

bookings.to_csv(fullname, header=True, index=False)
print("Saved!")

Saved!